---
services:
  api:
    image: "${API_IMAGE}"
    ports:
      - "0.0.0.0:25003:25003"
    networks:
      - "shared"

  worker:
    image: "${WORKER_IMAGE}"
    networks:
      - "shared"

networks:
  shared: {}
